// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/p-balachandran/kong-services/server/models"
)

// ServiceListOKCode is the HTTP code returned for type ServiceListOK
const ServiceListOKCode int = 200

/*
ServiceListOK List of Services

swagger:response serviceListOK
*/
type ServiceListOK struct {

	/*
	  In: Body
	*/
	Payload models.Services `json:"body,omitempty"`
}

// NewServiceListOK creates ServiceListOK with default headers values
func NewServiceListOK() *ServiceListOK {

	return &ServiceListOK{}
}

// WithPayload adds the payload to the service list o k response
func (o *ServiceListOK) WithPayload(payload models.Services) *ServiceListOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the service list o k response
func (o *ServiceListOK) SetPayload(payload models.Services) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ServiceListOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = models.Services{}
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// ServiceListBadRequestCode is the HTTP code returned for type ServiceListBadRequest
const ServiceListBadRequestCode int = 400

/*
ServiceListBadRequest Bad Request

swagger:response serviceListBadRequest
*/
type ServiceListBadRequest struct {
}

// NewServiceListBadRequest creates ServiceListBadRequest with default headers values
func NewServiceListBadRequest() *ServiceListBadRequest {

	return &ServiceListBadRequest{}
}

// WriteResponse to the client
func (o *ServiceListBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// ServiceListNotFoundCode is the HTTP code returned for type ServiceListNotFound
const ServiceListNotFoundCode int = 404

/*
ServiceListNotFound Services Not Found

swagger:response serviceListNotFound
*/
type ServiceListNotFound struct {
}

// NewServiceListNotFound creates ServiceListNotFound with default headers values
func NewServiceListNotFound() *ServiceListNotFound {

	return &ServiceListNotFound{}
}

// WriteResponse to the client
func (o *ServiceListNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// ServiceListInternalServerErrorCode is the HTTP code returned for type ServiceListInternalServerError
const ServiceListInternalServerErrorCode int = 500

/*
ServiceListInternalServerError Server Error

swagger:response serviceListInternalServerError
*/
type ServiceListInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewServiceListInternalServerError creates ServiceListInternalServerError with default headers values
func NewServiceListInternalServerError() *ServiceListInternalServerError {

	return &ServiceListInternalServerError{}
}

// WithPayload adds the payload to the service list internal server error response
func (o *ServiceListInternalServerError) WithPayload(payload string) *ServiceListInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the service list internal server error response
func (o *ServiceListInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ServiceListInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
