// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Kong Services
//
//	This is a take home assignmet for Kong Konnect. This service will list and retrieve service(s).
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /v1
//	Version: 0.0.1
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
