// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "swagger": "2.0",
  "info": {
    "description": "This is a take home assignmet for Kong Konnect. This service will list and retrieve service(s). ",
    "title": "Kong Services",
    "version": "0.0.1"
  },
  "basePath": "/v1",
  "paths": {
    "/services": {
      "get": {
        "description": "It returns a list of services",
        "summary": "Get all services",
        "operationId": "ServiceList",
        "responses": {
          "200": {
            "description": "List of Services",
            "schema": {
              "$ref": "#/definitions/Services"
            }
          },
          "400": {
            "description": "Bad Request"
          },
          "404": {
            "description": "Services Not Found"
          },
          "500": {
            "description": "Server Error",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Service": {
      "type": "object",
      "properties": {
        "description": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "serviceId": {
          "type": "integer"
        },
        "versions": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Version"
          }
        }
      }
    },
    "Services": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Service"
      }
    },
    "Version": {
      "type": "object",
      "properties": {
        "description": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "versionId": {
          "type": "integer"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "swagger": "2.0",
  "info": {
    "description": "This is a take home assignmet for Kong Konnect. This service will list and retrieve service(s). ",
    "title": "Kong Services",
    "version": "0.0.1"
  },
  "basePath": "/v1",
  "paths": {
    "/services": {
      "get": {
        "description": "It returns a list of services",
        "summary": "Get all services",
        "operationId": "ServiceList",
        "responses": {
          "200": {
            "description": "List of Services",
            "schema": {
              "$ref": "#/definitions/Services"
            }
          },
          "400": {
            "description": "Bad Request"
          },
          "404": {
            "description": "Services Not Found"
          },
          "500": {
            "description": "Server Error",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Service": {
      "type": "object",
      "properties": {
        "description": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "serviceId": {
          "type": "integer"
        },
        "versions": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Version"
          }
        }
      }
    },
    "Services": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Service"
      }
    },
    "Version": {
      "type": "object",
      "properties": {
        "description": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "versionId": {
          "type": "integer"
        }
      }
    }
  }
}`))
}
